# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

before_script:
  # Initialise virtualenv
  - python -V
  - pip -V
  - python -m venv venv
  - . venv/bin/activate
  - pip install wheel
  # Install synthreader requirements
  - pip install pytest
  - pip install coverage
  - pip install flake8
  # Install XDL and chemdata and XDL requirements
  - pip install git+https://$CHEMDATA_USER:$CHEMDATA_PW@gitlab.com/croningroup/chemputer/chemdata.git@master
  - pip install pyserial
  - pip install git+https://github.com/croningp/commanduino
  - pip install git+https://synthreader-ci:$COMMANDUINOLABWARE_PW@gitlab.com/croningroup/chemputer/commanduinolabware.git@master
  - pip install git+https://synthreader-ci:$SERIALLABWARE_PW@gitlab.com/croningroup/chemputer/seriallabware.git@master
  - pip install git+https://synthreader-ci:$CHEMPUTERAPI_PW@gitlab.com/croningroup/chemputer/chemputerapi.git@master
  - pip install git+https://synthreader-ci:$CHEMPILER_PW@gitlab.com/croningroup/chemputer/chempiler.git@master
  - pip install git+https://$XDL_USER:$XDL_PW@gitlab.com/croningroup/chemputer/xdl.git@master
  - pip install git+https://$CHEMPUTERXDL_USER:$CHEMPUTERXDL_PW@gitlab.com/croningroup/chemputer/chemputerxdl.git@master

  # Install synthreader
  - pip install .
  - python postinstall.py
  - pip freeze

lint:
  variables:
    FLAKE8_PER_FILE_IGNORE: tests/*:T001

  script:
    - pip install flake8
    - pip install flake8-print
    - flake8 . --per-file-ignores=$FLAKE8_PER_FILE_IGNORE

test:
  script:
    - coverage run --source=synthreader -m pytest tests/all_tests.py -m "fast_integration or unit" -x -rf
    - coverage report -m
