[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py37", "py38", "py39", "py310"]

[tool.isort]
profile = "black"

[tool.setuptools_scm]
