stages:
  - 'lint'
  - 'test'
  - 'deploy'

.test:
  before_script:
    - python -V
    - pip -V
    - python -m venv venv
    - . venv/bin/activate
    - pip install wheel
    - pip install pytest
    - pip install coverage

    # Install xdl requirements
    # Install Chempiler, SerialLabware and ChemputerAPI for simulations

    - pip install git+https://$CHEMPILER_USER:$CHEMPILER_PW@gitlab.com/croningroup/chemputer/chempiler.git@master

    - pip install git+https://$SERIALLABWARE_USER:$SERIALLABWARE_PW@gitlab.com/croningroup/chemputer/seriallabware.git@master

    - pip install git+https://$CHEMPUTERAPI_USER:$CHEMPUTERAPI_PW@gitlab.com/croningroup/chemputer/chemputerapi.git@master

    - pip install git+https://github.com/croningp/commanduino.git@master
    - pip install git+https://$COMMANDUINOLABWARE_USER:$COMMANDUINOLABWARE_PW@gitlab.com/croningroup/chemputer/commanduinolabware.git@master
    - pip install git+https://$XDL_USER:$XDL_PW@gitlab.com/croningroup/chemputer/xdl.git@master

    # Install chemputerxdl
    - pip install .
    - pip freeze

  script:
    - coverage run --source=chemputerxdl -m pytest tests -m "unit or integration or snapshot" -x -rf
    - coverage report -m

test-python:3.6:
  extends: '.test'
  stage: 'test'
  image: 'python:3.6'

test-python:3.7:
  extends: '.test'
  stage: 'test'
  image: 'python:3.7'

test-python:3.8:
  extends: '.test'
  stage: 'test'
  image: 'python:3.8'

lint:
  stage: 'lint'
  image: 'python:3.8'

  variables:
    FLAKE8_PER_FILE_IGNORE: tests/*:T001

  script:
    - pip install flake8
    - pip install flake8-print
    - flake8 . --per-file-ignores=$FLAKE8_PER_FILE_IGNORE

pages:
  stage: 'deploy'
  image: 'python:3.8'
  script:
    - pip install git+https://$CHEMPILER_USER:$CHEMPILER_PW@gitlab.com/croningroup/chemputer/chempiler.git@master
    - pip install networkx==2.2
    - pip install -U sphinx
    - pip install sphinx_rtd_theme
    - cd documentation
    - ./makedocs.sh
    - sphinx-build -b html -c ./ . ../public
  artifacts:
    paths:
      - public
  only:
    - master
