from typing import List

P_GENERAL_PHRASE_IS_REAGENT = 0.54

MIN_REAGENT_NAME_LENGTH = 2
MAX_REAGENT_NAME_LENGTH = 160

REAGENT_NAME_END_IGNORE_WORDS = [
    '(',
    ',',
]

REAGENT_NAME_IGNORE_WORD_LIST = set([
    'of',
    'in',
    'to',
    'at',
    'was',
    'and',
    'with',
    'carefully',
    'slowly',
    'approximately',
    'into',
    'by',
    'air',
    '.',
    'chromatography',
    'mixture',
    'precipitation',
    'containing',
    'temperature',
    'inert',
    'atmosphere',
    'under',
    'remove',
    'crystalline',
    'note',
    'internal',
    '°C',
    'then',
    'the',
    'vacuum',
    'filtration',
    'dry',
    'over',
    'techniques',
    'before',
    'schlenk',
    'hydrogenation',
    'evacuated',
    'pressure',
    'psi',
    'uptake',
    'further',
    'filtrate',
    'cannula',
    'diameter',
    'precipitated',
    'which',
    'hydrolysis',
    'eluent',
    'gradient',
    'tube',
    'remaining',
    'exercise',
    'pyrophoric',
    'can',
    'be',
    'so',
    'that',
    'allegedly',
    'typical',
    'after',
    'drying',
    'gives',
    'required',
    'varies',
    'produce',
    'does',
    'not',
    'cyclization',
    'corresponding',
    'desired',
    'receive',
    'as',
    'syn',
    'bath',
    'sides',
    'decanted',
    'inlet',
    'thermometer',
    'contaminated',
    'appropriate',
    'give',
    'leading',
    'Dean-Stark',
    'flame-dried',
    'magnetic',
    'should',
    'comes',
    'down',
    'material',
    'foaming',
    'entirely',
    'from',
    'free',
    ';',
    'mechanically',
    'method',
    'has',
    'any',
    'thus',
    'produced',
    'titrates',
    'crystallizes',
    'large',
    'cylinder',
    'manometer',
    'strip',
    'metal',
    'within',
    'solidifies',
    'same',
    'and',
    'separates',
    'been',
    'disappears',
    'until',
    'most',
    'distills',
    'coming',
    'allowed',
    'held',
    'siphoned',
    'little',
    'very',
    'remains',
    'directly',
    'followed',
    'employed',
    'afford',
    'yield',
    'vacuum',
    'source',
    'experiment',
    'additional',
    'preheated',
    'mantle',
    'purity',
    'procedure',
    'oval',
    'teflon',
    'using',
    'dryness',
    'voluminous',
    'without',
    'enantiomeric',
    'takes',
    'porosity',
])

REAGENT_NAME_AFTER_WORDS = [
    'solution',
    'gel',
    'suspension',
    'mixture',
    'powder',
    'hydrochloride',
    'pellets',
    'derivative',
]

REAGENT_NAME_BEFORE_WORDS = [
    ['half', 'saturated'],
    'half-saturated',
    'saturated',
    'concentrated',
    'diluted',
    'dilute',
    ['ice', 'cold'],
    ['very', 'cold'],
    'ice-cold',
    'icecold',
    'cold',
    'minimum',
    'the',
    'moist',
    'hot',
    'warm',
    'commercial',
    'deionized',
    'deionised',
    'glacial',
    'distilled',
    'sublimed',
    'dry',
    'anhydrous',
    'aqueous',
    'ice',
    'absolute',
    ['freshly', 'fused'],  # Seen in OrgSyn 'freshly fused sodium acetate'
    ['freshly', 'distilled'],
    'ethyl',
    'vinyl',
    ',',
    'n',
    '-',
]

#: Words that can't be the first word of a reagent name, but can be in a reagent
# name.
REAGENT_NAME_IGNORE_FIRST_WORD: List[str] = [
    ','
]

#: Characters that make
REAGENT_NAME_IGNORE_CHAR_LIST: List[str] = [
    '≈',
]
